# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/Console.ui'
#
# Created: Thu Aug 22 12:52:32 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 492)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../home/carlos/Eléctrica/CubeSat/PIC24FJ256GA110_EXT/TRANSCEIVER/branches/trx-v3/GUI/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEditSend = QtGui.QLineEdit(self.centralwidget)
        self.lineEditSend.setObjectName(_fromUtf8("lineEditSend"))
        self.gridLayout.addWidget(self.lineEditSend, 2, 2, 1, 1)
        self.pushButtonSend = QtGui.QPushButton(self.centralwidget)
        self.pushButtonSend.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("go-next"))
        self.pushButtonSend.setIcon(icon)
        self.pushButtonSend.setAutoDefault(True)
        self.pushButtonSend.setObjectName(_fromUtf8("pushButtonSend"))
        self.gridLayout.addWidget(self.pushButtonSend, 2, 5, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupConexion = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupConexion.sizePolicy().hasHeightForWidth())
        self.groupConexion.setSizePolicy(sizePolicy)
        self.groupConexion.setObjectName(_fromUtf8("groupConexion"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupConexion)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelBaudrate = QtGui.QLabel(self.groupConexion)
        self.labelBaudrate.setObjectName(_fromUtf8("labelBaudrate"))
        self.gridLayout_2.addWidget(self.labelBaudrate, 1, 0, 1, 1)
        self.pushButtonOpenPort = QtGui.QPushButton(self.groupConexion)
        self.pushButtonOpenPort.setObjectName(_fromUtf8("pushButtonOpenPort"))
        self.gridLayout_2.addWidget(self.pushButtonOpenPort, 2, 0, 1, 1)
        self.comboBoxPorts = QtGui.QComboBox(self.groupConexion)
        self.comboBoxPorts.setEditable(True)
        self.comboBoxPorts.setObjectName(_fromUtf8("comboBoxPorts"))
        self.gridLayout_2.addWidget(self.comboBoxPorts, 0, 1, 1, 1)
        self.pushButtonClosePort = QtGui.QPushButton(self.groupConexion)
        self.pushButtonClosePort.setEnabled(False)
        self.pushButtonClosePort.setObjectName(_fromUtf8("pushButtonClosePort"))
        self.gridLayout_2.addWidget(self.pushButtonClosePort, 2, 1, 1, 1)
        self.labePort = QtGui.QLabel(self.groupConexion)
        self.labePort.setObjectName(_fromUtf8("labePort"))
        self.gridLayout_2.addWidget(self.labePort, 0, 0, 1, 1)
        self.comboBoxBaudrate = QtGui.QComboBox(self.groupConexion)
        self.comboBoxBaudrate.setEditable(True)
        self.comboBoxBaudrate.setObjectName(_fromUtf8("comboBoxBaudrate"))
        self.gridLayout_2.addWidget(self.comboBoxBaudrate, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupConexion)
        self.groupBoxRepetir = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxRepetir.setObjectName(_fromUtf8("groupBoxRepetir"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxRepetir)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelPeriod = QtGui.QLabel(self.groupBoxRepetir)
        self.labelPeriod.setEnabled(False)
        self.labelPeriod.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPeriod.setObjectName(_fromUtf8("labelPeriod"))
        self.gridLayout_3.addWidget(self.labelPeriod, 3, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBoxRepetir)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 2, 0, 1, 2)
        self.spinBoxPeriod = QtGui.QSpinBox(self.groupBoxRepetir)
        self.spinBoxPeriod.setEnabled(False)
        self.spinBoxPeriod.setObjectName(_fromUtf8("spinBoxPeriod"))
        self.gridLayout_3.addWidget(self.spinBoxPeriod, 3, 1, 1, 1)
        self.checkBoxTimestamp = QtGui.QCheckBox(self.groupBoxRepetir)
        self.checkBoxTimestamp.setObjectName(_fromUtf8("checkBoxTimestamp"))
        self.gridLayout_3.addWidget(self.checkBoxTimestamp, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBoxRepetir)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.groupBoxCommand = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxCommand.setObjectName(_fromUtf8("groupBoxCommand"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxCommand)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.listWidgetCommand = QtGui.QListWidget(self.groupBoxCommand)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetCommand.sizePolicy().hasHeightForWidth())
        self.listWidgetCommand.setSizePolicy(sizePolicy)
        self.listWidgetCommand.setDragEnabled(True)
        self.listWidgetCommand.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidgetCommand.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidgetCommand.setAlternatingRowColors(True)
        self.listWidgetCommand.setObjectName(_fromUtf8("listWidgetCommand"))
        self.verticalLayout.addWidget(self.listWidgetCommand)
        self.horizontalLayout.addWidget(self.groupBoxCommand)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 5)
        self.checkBoxLF = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxLF.setChecked(True)
        self.checkBoxLF.setObjectName(_fromUtf8("checkBoxLF"))
        self.gridLayout.addWidget(self.checkBoxLF, 2, 3, 1, 1)
        self.checkBoxCR = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxCR.setObjectName(_fromUtf8("checkBoxCR"))
        self.gridLayout.addWidget(self.checkBoxCR, 2, 4, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 5, 6, 1, 1)
        self.textEditTerminal = QtGui.QTextEdit(self.centralwidget)
        self.textEditTerminal.setAutoFormatting(QtGui.QTextEdit.AutoAll)
        self.textEditTerminal.setTabChangesFocus(True)
        self.textEditTerminal.setUndoRedoEnabled(False)
        self.textEditTerminal.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEditTerminal.setLineWrapColumnOrWidth(0)
        self.textEditTerminal.setReadOnly(True)
        self.textEditTerminal.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.textEditTerminal.setObjectName(_fromUtf8("textEditTerminal"))
        self.gridLayout.addWidget(self.textEditTerminal, 4, 2, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuHerramientas = QtGui.QMenu(self.menubar)
        self.menuHerramientas.setObjectName(_fromUtf8("menuHerramientas"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionGuardar = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionGuardar.setIcon(icon)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionSalir = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.actionSalir.setIcon(icon)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionAgregar_comando = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("list-add"))
        self.actionAgregar_comando.setIcon(icon)
        self.actionAgregar_comando.setObjectName(_fromUtf8("actionAgregar_comando"))
        self.actionAcerca_de = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-about"))
        self.actionAcerca_de.setIcon(icon)
        self.actionAcerca_de.setObjectName(_fromUtf8("actionAcerca_de"))
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuHerramientas.addAction(self.actionAgregar_comando)
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.labelBaudrate.setBuddy(self.comboBoxBaudrate)
        self.labePort.setBuddy(self.comboBoxPorts)
        self.labelPeriod.setBuddy(self.spinBoxPeriod)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.textEditTerminal.clear)
        QtCore.QObject.connect(self.lineEditSend, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.pushButtonSend.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBoxPorts, self.comboBoxBaudrate)
        MainWindow.setTabOrder(self.comboBoxBaudrate, self.pushButtonOpenPort)
        MainWindow.setTabOrder(self.pushButtonOpenPort, self.pushButtonClosePort)
        MainWindow.setTabOrder(self.pushButtonClosePort, self.lineEditSend)
        MainWindow.setTabOrder(self.lineEditSend, self.pushButtonSend)
        MainWindow.setTabOrder(self.pushButtonSend, self.checkBoxLF)
        MainWindow.setTabOrder(self.checkBoxLF, self.checkBoxCR)
        MainWindow.setTabOrder(self.checkBoxCR, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.textEditTerminal)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Commander", None))
        self.pushButtonSend.setText(_translate("MainWindow", "Enviar", None))
        self.groupConexion.setTitle(_translate("MainWindow", "Conexión", None))
        self.labelBaudrate.setText(_translate("MainWindow", "Tasa de datos", None))
        self.pushButtonOpenPort.setText(_translate("MainWindow", "Abrir", None))
        self.pushButtonClosePort.setText(_translate("MainWindow", "Cerrar", None))
        self.labePort.setText(_translate("MainWindow", "Puerto", None))
        self.groupBoxRepetir.setTitle(_translate("MainWindow", "Opciones", None))
        self.labelPeriod.setText(_translate("MainWindow", "Periodo", None))
        self.checkBox.setText(_translate("MainWindow", "Modo continuo", None))
        self.spinBoxPeriod.setSuffix(_translate("MainWindow", " [s]", None))
        self.checkBoxTimestamp.setText(_translate("MainWindow", "Agregar marca de tiempo", None))
        self.groupBoxCommand.setTitle(_translate("MainWindow", "Lista de comandos", None))
        self.checkBoxLF.setText(_translate("MainWindow", "LF", None))
        self.checkBoxCR.setText(_translate("MainWindow", "CR", None))
        self.pushButton.setText(_translate("MainWindow", "Limpiar", None))
        self.textEditTerminal.setDocumentTitle(_translate("MainWindow", "Log", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.menuHerramientas.setTitle(_translate("MainWindow", "Herramientas", None))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda", None))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar", None))
        self.actionGuardar.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSalir.setText(_translate("MainWindow", "Salir", None))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAgregar_comando.setText(_translate("MainWindow", "Agregar comando", None))
        self.actionAgregar_comando.setShortcut(_translate("MainWindow", "Ctrl+Shift+A", None))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de", None))

